// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace msg {

namespace {

const ::google::protobuf::Descriptor* AddrResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AddrResponse_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msg_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_msg_2eproto() {
  protobuf_AddDesc_msg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msg.proto");
  GOOGLE_CHECK(file != NULL);
  AddrResponse_descriptor_ = file->message_type(0);
  static const int AddrResponse_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AddrResponse, addresses_),
  };
  AddrResponse_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      AddrResponse_descriptor_,
      AddrResponse::default_instance_,
      AddrResponse_offsets_,
      -1,
      -1,
      -1,
      sizeof(AddrResponse),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AddrResponse, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AddrResponse, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      AddrResponse_descriptor_, &AddrResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msg_2eproto() {
  delete AddrResponse::default_instance_;
  delete AddrResponse_reflection_;
}

void protobuf_AddDesc_msg_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_msg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tmsg.proto\022\003msg\"!\n\014AddrResponse\022\021\n\taddr"
    "esses\030\001 \003(\tb\006proto3", 59);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg.proto", &protobuf_RegisterTypes);
  AddrResponse::default_instance_ = new AddrResponse();
  AddrResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msg_2eproto {
  StaticDescriptorInitializer_msg_2eproto() {
    protobuf_AddDesc_msg_2eproto();
  }
} static_descriptor_initializer_msg_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AddrResponse::kAddressesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AddrResponse::AddrResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:msg.AddrResponse)
}

void AddrResponse::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

AddrResponse::AddrResponse(const AddrResponse& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:msg.AddrResponse)
}

void AddrResponse::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
}

AddrResponse::~AddrResponse() {
  // @@protoc_insertion_point(destructor:msg.AddrResponse)
  SharedDtor();
}

void AddrResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void AddrResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AddrResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AddrResponse_descriptor_;
}

const AddrResponse& AddrResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_2eproto();
  return *default_instance_;
}

AddrResponse* AddrResponse::default_instance_ = NULL;

AddrResponse* AddrResponse::New(::google::protobuf::Arena* arena) const {
  AddrResponse* n = new AddrResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AddrResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.AddrResponse)
  addresses_.Clear();
}

bool AddrResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:msg.AddrResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string addresses = 1;
      case 1: {
        if (tag == 10) {
         parse_addresses:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_addresses()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->addresses(this->addresses_size() - 1).data(),
            this->addresses(this->addresses_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "msg.AddrResponse.addresses"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_addresses;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:msg.AddrResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:msg.AddrResponse)
  return false;
#undef DO_
}

void AddrResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:msg.AddrResponse)
  // repeated string addresses = 1;
  for (int i = 0; i < this->addresses_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->addresses(i).data(), this->addresses(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "msg.AddrResponse.addresses");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->addresses(i), output);
  }

  // @@protoc_insertion_point(serialize_end:msg.AddrResponse)
}

::google::protobuf::uint8* AddrResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.AddrResponse)
  // repeated string addresses = 1;
  for (int i = 0; i < this->addresses_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->addresses(i).data(), this->addresses(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "msg.AddrResponse.addresses");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->addresses(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:msg.AddrResponse)
  return target;
}

int AddrResponse::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:msg.AddrResponse)
  int total_size = 0;

  // repeated string addresses = 1;
  total_size += 1 * this->addresses_size();
  for (int i = 0; i < this->addresses_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->addresses(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AddrResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:msg.AddrResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const AddrResponse* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const AddrResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:msg.AddrResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:msg.AddrResponse)
    MergeFrom(*source);
  }
}

void AddrResponse::MergeFrom(const AddrResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:msg.AddrResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  addresses_.MergeFrom(from.addresses_);
}

void AddrResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:msg.AddrResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AddrResponse::CopyFrom(const AddrResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.AddrResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddrResponse::IsInitialized() const {

  return true;
}

void AddrResponse::Swap(AddrResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AddrResponse::InternalSwap(AddrResponse* other) {
  addresses_.UnsafeArenaSwap(&other->addresses_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AddrResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AddrResponse_descriptor_;
  metadata.reflection = AddrResponse_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AddrResponse

// repeated string addresses = 1;
int AddrResponse::addresses_size() const {
  return addresses_.size();
}
void AddrResponse::clear_addresses() {
  addresses_.Clear();
}
 const ::std::string& AddrResponse::addresses(int index) const {
  // @@protoc_insertion_point(field_get:msg.AddrResponse.addresses)
  return addresses_.Get(index);
}
 ::std::string* AddrResponse::mutable_addresses(int index) {
  // @@protoc_insertion_point(field_mutable:msg.AddrResponse.addresses)
  return addresses_.Mutable(index);
}
 void AddrResponse::set_addresses(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:msg.AddrResponse.addresses)
  addresses_.Mutable(index)->assign(value);
}
 void AddrResponse::set_addresses(int index, const char* value) {
  addresses_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:msg.AddrResponse.addresses)
}
 void AddrResponse::set_addresses(int index, const char* value, size_t size) {
  addresses_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:msg.AddrResponse.addresses)
}
 ::std::string* AddrResponse::add_addresses() {
  // @@protoc_insertion_point(field_add_mutable:msg.AddrResponse.addresses)
  return addresses_.Add();
}
 void AddrResponse::add_addresses(const ::std::string& value) {
  addresses_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:msg.AddrResponse.addresses)
}
 void AddrResponse::add_addresses(const char* value) {
  addresses_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:msg.AddrResponse.addresses)
}
 void AddrResponse::add_addresses(const char* value, size_t size) {
  addresses_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:msg.AddrResponse.addresses)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
AddrResponse::addresses() const {
  // @@protoc_insertion_point(field_list:msg.AddrResponse.addresses)
  return addresses_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
AddrResponse::mutable_addresses() {
  // @@protoc_insertion_point(field_mutable_list:msg.AddrResponse.addresses)
  return &addresses_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msg

// @@protoc_insertion_point(global_scope)
